#green
version: '3'
services:
  order-manage-server:
    build: .
    ports:
      - "8082:8080"
    container_name: order-manage-server-green

  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"
