#green
version: '3'
services:
  order-manage-server:
    build: .
    ports:
      - "8082:8080"
      - "8090:8090"
    image: order-manage-server
    container_name: order-manage-server-green
    restart: always

networks:
  default:
    name: order-manage-server-bridge
    external: true
