#blue
# 최신 소프트웨어를 사용하기 위하여 버전 3 사용
version: '3'
services:
  # 서비스의 이름
  order-manage-server:
    # 현재 디렉토리에서의 Dockerfile을 사용하여 Docker 이미지를 빌드
    build: .
    # 호스트의 8081 포트와 컨테이너의 8080 포트를 매핑
    ports:
      - "8081:8080"
    # 컨테이너의 이름
    container_name: order-manage-server-blue

networks:
  default:
    external:
      name: order-manage-server-bridge
